export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/profile', component: require('./components/Profile.vue').default },
    { path: '/developer', component: require('./components/Developer.vue').default },
    { path: '/users', component: require('./components/Users.vue').default },
    { name: 'products', path: '/products', component: require('./components/product/Products.vue').default },
    { path: '/product/tag', component: require('./components/product/Tag.vue').default },
    { path: '/product/category', component: require('./components/product/Category.vue').default },
    { path: '*', component: require('./components/NotFound.vue').default },
    { path: '/orders', component: require('./components/order/Orders.vue').default },
    { path: '/web-orders', component: require('./components/order/WebOrders.vue').default },
    { path: '/processing-orders', component: require('./components/order/ProcessingOrders.vue').default },
    { path: '/pending-payment-orders', component: require('./components/order/PendingPaymentOrders.vue').default },
    { path: '/on-hold-orders', component: require('./components/order/OnHoldOrders.vue').default },
    { path: '/in-transit-orders', component: require('./components/order/InTransitOrders.vue').default },
    { path: '/delivered-orders', component: require('./components/order/DeliveredOrders.vue').default },
    { path: '/returned-orders', component: require('./components/order/ReturnedOrders.vue').default },
    { path: '/completed-orders', component: require('./components/order/CompletedOrders.vue').default },
    { path: '/cancelled-orders', component: require('./components/order/CancelledOrders.vue').default },
    { path: '/refunded-orders', component: require('./components/order/RefundedOrders.vue').default },
    { path: '/failed-orders', component: require('./components/order/FailedOrders.vue').default },
    { path: '/confirmed-orders', component: require('./components/order/ConfirmedOrders.vue').default },
    { path: '/payment-methods', component: require('./components/order/PaymentMethods.vue').default },
    { path: '/shipping-titles', component: require('./components/order/ShippingTitles.vue').default },
    { path: '/shop-setting', component: require('./components/ShopSetting.vue').default },
    { path: '/generate-pdf', component: require('./components/GeneratePDF.vue').default },
];
